### ISSUE TITLE
config-resolver.js - Consider moving declaration of 'info' as it is referenced outside current binding context.

### ISSUE THREAD

**Issue by liamfranke** [brettjanz/SENG-371-M1-hygen#10]
<img width="882" alt="Screen Shot 2022-03-18 at 11 24 49 AM" src="https://user-images.githubusercontent.com/59858446/159065680-2a6fc1d3-6c62-45db-a2f9-3a350139e371.png">

Refactor Method:

Rewrite the code to be more legible and digestible for developers, as it takes place entirely inline. Move declaration of var info to above try statement where it is declared, to ensure that is is referenced within current binding context

**Comment by brettjanz** [comment]
Tested in src/__tests__/config.spec.ts

**Comment by liamfranke** [comment]
Included Incorrect Screenshot
