### ISSUE TITLE
config.js - Consider Moving Declaration of '_iterator' as it is referenced outside of current binding context

### ISSUE THREAD

**Issue by liamfranke** [brettjanz/SENG-371-M1-hygen#6]
<img width="882" alt="Screen Shot 2022-03-18 at 11 24 49 AM" src="https://user-images.githubusercontent.com/59858446/159061883-3271360d-7391-436c-be67-8c015615e66a.png">

Refactor Method:

Declare var _iterator above the try statement, underneath var _iteratorError, so it is continually referenced within current context

**Comment by brettjanz** [comment]
Tested in src/__tests__/config.spec.ts
