### ISSUE TITLE
inject.js - 'Inject' is already declared in the upper scope

### ISSUE THREAD

**Issue by liamfranke** [brettjanz/SENG-371-M1-hygen#7]
<img width="884" alt="Screen Shot 2022-03-18 at 11 34 59 AM" src="https://user-images.githubusercontent.com/59858446/159063279-3947813d-aed9-4d9d-85e0-41a485472299.png">

Refactor Method: 

As this is an issue of shadowing an upper scope variable, the refactor method will be to rename the secondary inject variable so it no longer matches the initial 'inject' declaration

**Comment by brettjanz** [comment]
Tested in src/__tests__/injector.spec.ts
